version: "3.8"

services:
  config-server:
    image: turkcell-configserver
    build: ./config-server
    ports:
      - 32087:8787
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8787/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
  eureka-server:
    image: turkcell-eurekaserver
    build: ./eureka-server
    ports:
      - 32086:8761
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8787