spring:
  kafka:
    bootstrap-servers: localhost:9094
  datasource:
    url: "jdbc:postgresql://localhost:5435/catalog-service"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8003/realms/turkcell-ecommerce-dev
  data:
    redis:
      uri: redis://localhost:6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans