spring:
  datasource:
    url: "jdbc:postgresql://localhost:32089/product-db"
    username: postgres
    password: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32086/eureka/